version: "3.3"

services:
  neo:
    image: neo4j:latest
    # ports:
    #   - 7474:7474
    #   - 7687:7687
    volumes:
      - neo4j_data:/data/
    env_file:
      - .env.neo4j
    networks:
      db_net:
        ipv4_address: 172.16.238.2
        ipv6_address: 2001:3984:3989::10

  bible-reference-api:
    image: dfields2016/bible-reference-explorer-api:master
    depends_on:
      - neo
    ports:
      - 8080:8080
    networks:
      db_net:
        ipv4_address: 172.16.238.3
        ipv6_address: 2001:3984:3989::11

  bible-reference-ui:
    image: dfields2016/bible-reference-explorer-ui:master
    depends_on:
      - neo
      - bible-reference-api
    ports:
      - 3000:80
    networks:
      db_net:
        ipv4_address: 172.16.238.4
        ipv6_address: 2001:3984:3989::12

  nginx:
    image: dfields2016/bible-reference-explorer-infra:master
    depends_on:
      - bible-reference-api
      - bible-reference-ui
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      db_net:
        ipv4_address: 172.16.238.5
        ipv6_address: 2001:3984:3989::13
    volumes:
    # - ./data/nginx:/etc/nginx/conf.d
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  neo4j_data:

networks:
  db_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1