# name: Deploy Bible Reference Infrastructure

# on:
#   push:
#     branches:
#       - master

# jobs:
#   push_to_registry:
#     name: Build/Push Docker Img
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#         with:
#           images: dfields2016/bible-reference-explorer-infra

#       - name: Build and push Docker image
#         uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}

#   update_ssh_linode:
#     name: Update Linode Server
#     needs: "push_to_registry"
#     runs-on: ubuntu-latest
#     steps:
#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.HOST_USERNAME }}
#         password: ${{ secrets.HOST_PASSWORD }}
#         port: ${{ secrets.HOST_PORT }}
#         script: sleep 60 && curl https://raw.githubusercontent.com/dfields16/bible-reference-explorer-infra/master/scripts/update-infra.sh > update-infra.sh && bash update-infra.sh